DROP TABLE IF EXISTS movie;

CREATE TABLE movie (

  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  description TEXT,
  year_released VARCHAR(255),
  img_url TEXT

);

INSERT INTO movie (title , description, year_released, img_url) VALUES ('Ant-Man and Wasp' , 'Ant-Man and the Wasp is a 2018 American superhero film based on the Marvel Comics characters Scott Lang / Ant-Man and Hope van Dyne / Wasp. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the sequel to 2015s Ant-Man, and the twentieth film in the Marvel Cinematic Universe (MCU). The film is directed by Peyton Reed and written by the writing teams of Chris McKenna and Erik Sommers, and Paul Rudd, Andrew Barrer, and Gabriel Ferrari. It stars Rudd as Lang and Evangeline Lilly as Van Dyne, alongside Michael Peña, Walton Goggins, Bobby Cannavale, Judy Greer, Tip "T.I." Harris, David Dastmalchian, Hannah John-Kamen, Abby Ryder Fortson, Randall Park, Michelle Pfeiffer, Laurence Fishburne, and Michael Douglas. In Ant-Man and the Wasp, the titular pair work with Hank Pym to retrieve Janet van Dyne from the quantum realm..','2018','https://nerdist.com/wp-content/uploads/2018/07/ant-man-and-the-wasp-spoilers.jpg');
INSERT INTO movie (title , description, year_released, img_url) VALUES ('Incredibles 2' , 'Incredibles 2 is a 2018 American 3D computer-animated superhero film produced by Pixar Animation Studios and released by Walt Disney Pictures. Written and directed by Brad Bird, it is the sequel to 2004s The Incredibles and second installment of the franchise. The plot picks up directly after the events of the first film and follows the Parr family as they balance regaining the publics trust of superheroes with their civilian family life, only to combat a new foe who seeks to turn the populace against all supers. The voice cast includes Craig T. Nelson, Holly Hunter, Sarah Vowell and Samuel L. Jackson, who reprise their roles from the first film, while newcomers to the cast include Huckleberry Milner (replacing Spencer Fox), Bob Odenkirk, Catherine Keener and Jonathan Banks (replacing Bud Luckey). The films score was composed by Michael Giacchino, who had worked on the music for the previous film.','2018', 'https://static.goldderby.com/wp-content/uploads/2018/06/Incredibles-2-Pixar-620x360.jpg');
INSERT INTO movie (title , description, year_released, img_url) VALUES ('The spy who dumped me' , 'The Spy Who Dumped Me is a 2018 American action comedy film directed by Susanna Fogel and co-written by Fogel and David Iserson. The film stars Mila Kunis, Kate McKinnon, Justin Theroux, Sam Heughan, Hasan Minhaj and Gillian Anderson and follows two best friends who are chased through Europe by assassins after one of their ex-boyfriends turns out to be a CIA agent. The film was released in the United States on August 3, 2018, by Lionsgate. It has grossed over $52 million and received mixed reviews from critics, who questioned the films intended genre and tone but praised the performances.','year_released', 'https://cdn.flickeringmyth.com/wp-content/uploads/2018/06/Spy-Who-Dumped-Me-UK-poster-600x450.jpg');
INSERT INTO movie (title , description, year_released, img_url) VALUES ('Mamma Mia! Here we go' , 'Mamma Mia! Here We Go Again is a 2018 jukebox musical romantic comedy film written and directed by Ol Parker, from a story by Parker, Catherine Johnson, and Richard Curtis. It is a follow-up to the 2008 film Mamma Mia!, which in turn is based on the musical of the same name using the music of ABBA. The film features an ensemble cast, including Lily James, Amanda Seyfried, Christine Baranski, Julie Walters, Pierce Brosnan, Andy García, Dominic Cooper, Colin Firth, Stellan Skarsgård, Jessica Keenan Wynn, Alexa Davies, Jeremy Irvine, Hugh Skinner, Josh Dylan, Cher, and Meryl Streep. Both a prequel and a sequel, the plot is set after the events of the first film, and also features flashbacks to 1979, telling the story of Donna Sheridans arrival on the island of Kalokairi and her first meetings with her daughter Sophies three possible fathers.','year_released', 'https://www.hertfordtheatre.com/system/expressionengine/third_party/eventmanager/images/normals/mama_mia_quad.jpg');
